---
title: "Twitter Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(plotly)
tweet_data <- read.csv("D:/term 2/Data Visulization/datasets/narendramodi_tweets.csv")

```

row
-----------------------------------------------------------------------

### Followers

```{r}
valueBox(10000,icon ="fa-users")
```

### Total Tweets
```{r}
valueBox(5000,icon = "fa-pencil",color = "green")
```

### Average retweets
```{r}
valueBox(10100,icon = "fa-retweet",color = "orange")
```

row
-----------------
### Chart D

```{r}

a <- ggplot(tweet_data,aes(x = retweets_count,y = favorite_count,col=factor(source)))+geom_point()
ggplotly(a)

```

row
------------------
### Frequently used Words :wordcloud

```{r}
library(tm)
library(SnowballC)
library(wordcloud)
common_stop_words <- stopwords()
#length(common_stop_words)


#remove all stop words 
tweet_data$text <- as.character(tweet_data$text)
words_freq <- table(unlist(strsplit(tweet_data$text,' ')))
words_freq <- as.data.frame(words_freq)
names(words_freq) <- c('words','freq')
words_top <- words_freq %>% filter(!words_freq$words %in% common_stop_words) %>% arrange(-freq) %>% head(50)

wordcloud(words_top$words,words_top$freq,colors = words_top$freq)
```

### Text Starting with '#' tags
```{r}
hasttag_words <- words_freq[startsWith(as.character(words_freq$words),'#'),]

hastags_words_top <- hasttag_words %>% arrange(-freq) %>% head(50)
wordcloud(hastags_words_top$words,hastags_words_top$freq,colors = hastags_words_top$freq)
```

